services:
  postgres16:
    image: "postgres:16"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - postgres_16_data:/var/lib/postgresql/data
      
volumes:
  postgres_16_data:
  
